vich_uploader:
    db_driver: orm

    mappings:
        pin_image:
           uri_prefix: /uploads/pins
           upload_destination: '%kernel.project_dir%/public/uploads/pins'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true
        comment_file:
           uri_prefix: /uploads/comment
           upload_destination: '%kernel.project_dir%/public/uploads/comment'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true

    metadata:
        type: attribute
